//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.09 at 01:36:09 PM EET 
//


package demo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Game_QNAME = new QName("", "game");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Moves }
     * 
     */
    public Moves createMoves() {
        return new Moves();
    }

    /**
     * Create an instance of {@link MoveContent }
     * 
     */
    public MoveContent createMoveContent() {
        return new MoveContent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Moves }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game")
    public JAXBElement<Moves> createGame(Moves value) {
        return new JAXBElement<Moves>(_Game_QNAME, Moves.class, null, value);
    }

}
